var testdata = {
  "_id": "ChzKxTd3zi9AbGyRx",
  "data": [
    {
      "name": "Catwoman",
      "course_number": 16,
      "gender": "F",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Mystique",
      "course_number": 6,
      "gender": "F",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Bane",
      "course_number": 6,
      "gender": "M",
      "year": "2016",
      "group": 2,
    },
    {
      "name": "The Riddler",
      "course_number": 16,
      "gender": "M",
      "year": "2016",
      "group": 6,
    },
    {
      "name": "Sandman",
      "course_number": 2,
      "gender": "M",
      "year": "2016",
      "group": 6,
    },
    {
      "name": "Joker",
      "course_number": 2,
      "gender": "M",
      "year": "2015",
      "group": 2,
    },
    {
      "name": "Doctor Doom",
      "course_number": 6,
      "gender": "M",
      "year": "2015",
      "group": 5,
    },
    {
      "name": "Lex Luther",
      "course_number": 1,
      "gender": "M",
      "year": "2016",
      "group": 5,
    },
    {
      "name": "Galactus",
      "course_number": 16,
      "gender": "M",
      "year": "2016",
      "group": 2,
    },
    {
      "name": "Loki",
      "course_number": 6,
      "gender": "M",
      "year": "2015",
      "group": 5,
    },
    {
      "name": "Ironman",
      "course_number": 7,
      "gender": "M",
      "year": "2016",
      "group": 4,
    },
    {
      "name": "Aquaman",
      "course_number": 8,
      "gender": "M",
      "year": "2016",
      "group": 6,
    },
    {
      "name": "Hercules",
      "course_number": 22,
      "gender": "M",
      "year": "2015",
      "group": 4,
    },
    {
      "name": "Wolverine",
      "course_number": 2,
      "gender": "M",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Magneto",
      "course_number": 2,
      "gender": "M",
      "year": "2016",
      "group": 4,
    },
    {
      "name": "Thor",
      "course_number": 20,
      "gender": "M",
      "year": "2016",
      "group": 5,
    },
    {
      "name": "Hal Jordan",
      "course_number": 16,
      "gender": "M",
      "year": "2017",
      "group": 2,
    },
    {
      "name": "Wonder Woman",
      "course_number": 6,
      "gender": "F",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Captain America",
      "course_number": 6,
      "gender": "M",
      "year": "2018",
      "group": 4,
    },
    {
      "name": "Hulk",
      "course_number": 7,
      "gender": "M",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Dale",
      "course_number": 6,
      "gender": "M",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Batman",
      "course_number": 3,
      "gender": "M",
      "year": "2016",
      "group": 1,
    },
    {
      "name": "Robin",
      "course_number": 9,
      "gender": "M",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Superman",
      "course_number": 18,
      "gender": "M",
      "year": "2015",
      "group": 6,
    },
    {
      "name": "Spiderman",
      "course_number": 16,
      "gender": "M",
      "year": "2016",
      "group": 0,
    },
    {
      "name": "Pluto",
      "course_number": 6,
      "gender": "M",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Scrooge Matt",
      "course_number": 2,
      "gender": "M",
      "year": "2017",
      "group": 1,
    },
    {
      "name": "Tom",
      "course_number": 2,
      "gender": "M",
      "year": "2018",
      "group": 1,
    },
    {
      "name": "Jerry",
      "course_number": 5,
      "gender": "M",
      "year": "2016",
      "group": 0,
    },
    {
      "name": "Chip",
      "course_number": 10,
      "gender": "M",
      "year": "2015",
      "group": 1,
    },
    {
      "name": "Mickey Mouse",
      "course_number": 6,
      "gender": "M",
      "year": "2016",
      "group": 0,
    },
    {
      "name": "Minnie Mouse",
      "course_number": 6,
      "gender": "F",
      "year": "2015",
      "group": 3,
    },
    {
      "name": "Donald Duck",
      "course_number": 2,
      "gender": "M",
      "year": "2015",
      "group": 3,
    },
    {
      "name": "Daisy Duck",
      "course_number": 3,
      "gender": "F",
      "year": "2016",
      "group": 3,
    },
    {
      "name": "Goofy",
      "course_number": 1,
      "gender": "M",
      "year": "2017",
      "group": 0,
    }
  ],
  "settings": {
    "priorities": [
      "gender",
      "course_number",
      "year",
      "name",
      "group",
      "sports_team"
    ]
  },
  "name": "dmans-other-test-group",
  "filterObj": null,
  "filters": {
    "name": [
      "Catwoman",
      "Goofy",
      "Bane",
      "The Riddler",
      "Sandman",
      "Joker",
      "Doctor Doom",
      "Lex Luther",
      "Galactus",
      "Loki",
      "Ironman",
      "Aquaman",
      "Hercules",
      "Wolverine",
      "Magneto",
      "Thor",
      "Hal Jordan",
      "Mystique",
      "Captain America",
      "Hulk",
      "Dale",
      "Batman",
      "Robin",
      "Superman",
      "Spiderman",
      "Pluto",
      "Scrooge Matt",
      "Tom",
      "Jerry",
      "Chip",
      "Mickey Mouse",
      "Minnie Mouse",
      "Donald Duck",
      "Daisy Duck",
      "Wonder Woman"
    ],
    "course_number": [
      1,
      2,
      3,
      5,
      6,
      7,
      8,
      9,
      10,
      16,
      18,
      20,
      22
    ],
    "gender": [
      "F",
      "M"
    ],
    "year": [
      "2015",
      "2016",
      "2017",
      "2018"
    ],
    "group": [
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ]
  }
};